version: "3"

services:
  app:
    build: .
    tty: true
    ports:
      - "3000:3000"
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/rails
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  db_data:
